tree-sitter/tree-sitter-scala

corpus/expressions.txt
grammar.js
src/grammar.json
src/node-types.json

allow val def at start of lambda

---

.github/workflows/ci.yml

Problem
-------
Currently CI is failing on windows-latest.
Solution
--------
Downgrade to windows-2019 so node-gyp can be installed.

Fix Github Actions on Windows

---

.github/workflows/ci.yml
.gitignore
corpus/definitions.txt
corpus/expressions.txt
grammar.js
src/grammar.json
src/node-types.json
src/scanner.c
src/stack.h
test/test-stack.c

Ref https://github.com/tree-sitter/tree-sitter-scala/issues/43
Problem
-------
Currently Scala 3 optional braces syntax does not work.
Specifically, in this PR I want to address decls/defns not properly grouped under the right owner in part 1 (#61).
Solution
--------
1. This brings in indent/outdent impl by @keynmol
2. Introduce `_indentable_expression`.
This allows us to limit where indent/outdent shows up without
confusing tree-sitter too much.
Internally I've made a change to track `last_indentation_size` in the payload to indicate last
outdent (default: -1). If it's not -1 that means there was an outdent.
This then checks if the last_indentation_size qualified for another outdent.
2. Add support for control strctures:
The test cases for these are:
```lisp …
```

Optional braces, part 2

---

grammar.js
src/grammar.json
src/node-types.json

Copy of https://github.com/tree-sitter/tree-sitter-scala/pull/51 but I force-pushed the branch on a closed PR and can no longer reopen it.

Backquoted identifiers

---

.github/workflows/ci.yml
script/smoke_test.sh

This adds real-world integration test using scala/scala and Dotty compiler code base.
The expected parse success% is currently hardcoded, but at least we'll catch if this number degrades.

Smoke test

---

.github/workflows/ci.yml

Problem
-------
For some reason code generation doesn't seem to work on Linux, thus PRs without the generated code fails the test.
Solution
--------
Switch to using macOS.

Use macOS for testing instead

---

corpus/definitions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/71
Scala 3 syntax uses `using` to denote implicit parameters.
Allow both `implicit` and `using`.
This improves Dotty parsing success% (tested using https://github.com/tree-sitter/tree-sitter-scala/pull/81) from 35.68% to 56.81%

Using clauses

---

corpus/types.txt
grammar.js

I had to separate null and non null because the former cannot be a literal type 
Closes #84

Literal types

---

grammar.js
src/grammar.json
src/node-types.json

This reverts a change made in
https://github.com/tree-sitter/tree-sitter-scala/commit/fa8d64b77ed9a53067317eb69725b61bf2c634b1#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbL140-R142
where we introduced `_arrow`. This change will break the current neovim
highlights and we don't need it to be a named node.
refs: https://github.com/nvim-treesitter/nvim-treesitter/pull/4113

fix: remove hidden arrow node

---

.github/workflows/ci.yml

Ref https://github.com/tree-sitter/tree-sitter-scala/issues/85
Ref https://github.com/tree-sitter/tree-sitter-scala/pull/94
Problem
-------
Currently the diff change detection is broken because it fails
when the changes are empty.
Solution
--------
1. Fix the logic.
2. Include the file names in the error message.
3. Run diff

Fix the diff change detection 

---

Cargo.toml
bindings/rust/lib.rs
package.json
script/smoke_test.sh

This is a resend of #100 minus a generated file.

Bump tree sitter to 0.20.7 and expose highlights query in rust binding, take 3

---

grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/97
Problem
-------
Currently codegen uses 34GB, which is more than my desktop can handle. ahlinc kindly let us know about `--report-states-for-rule` flag to try to identify some choke points.
To my surprise `class_definition` uses 3728 states - https://gist.github.com/eed3si9n/009b1e5f11f5a80ea2c98d030bd25e13
Solution
--------
This adds intermediate node called `_class_constructor`, which is right associated to deal with the modifiers, but now `class_definition` can be left associated.
After this change:
```
$ /usr/bin/time -f "%M" node_modules/.bin/tree-sitter generate
11723152
```
This brings down memory usage to 11GB.

Optimize codegen memory usage

---

grammar.js
queries/highlights.scm
test/highlight/basics.scala
test/highlight/scala3.scala

closes #98 
The highlighting queries in this repo are out of date with the version in nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/scala/highlights.scm
That version has some issues, so I used it as the bases and moved/simplified/added rules.
In particular we are more precise about highlighting identifiers (before they would be aggressively highlighted as variable in lots of places)
I feel like we should grow the test coverage of highlighting queries, and once we're satisfied - upstream the changes
```
cp queries/* ~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/scala/
```
The difference are subtle (and some identifiers have the correct highlighting only because they're capitalised), but in particular class/enum parameters and …

Sync and improve highlighting queries, add Scala 3 specific constructs and tests

---

corpus/definitions.txt
grammar.js
script/smoke_test.sh

This does bring up the coverage, but unfortunately this handling of operator_identifier caused issues in prefix_expression tests.
I'm not sure how to fix the tests.
Another option would be to perhaps do `_identifier_like: $ => choice($.identifier, $.operator_identifier)` but this takes us further away from what Scala syntax is like.

Vararg class params and operator identifiers

---

corpus/definitions.txt
grammar.js
queries/highlights.scm
test/highlight/scala3.scala

Seems like I missed it originally.
Now the reference enum looks _perfect_:

Scala 3 enums: fix simple case inheritance

---

corpus/definitions.txt
corpus/expressions.txt
grammar.js
queries/highlights.scm
test/highlight/scala3.scala

Same as #44 - I'm still figuring out Tree Sitter (reading docs) so please do tell how to do this better.
I think adding two conflicts severely affected the parser build time (which wasn't fast before).
Code:
```scala
inline def test(inline c: Char) = 
inline c match {
case 'a' => 1
case 'b' => 2
}
inline def test1(inline c: Char) = 
inline if (c == 'h') {}
```
<details><summary>Before</summary><pre><code>
ERROR [0, 0] - [0, 6]
identifier [0, 0] - [0, 6]
function_definition [0, 7] - [8, 6]
name: identifier [0, 11] - [0, 15]
parameters: parameters [0, 15] - [0, 31]
parameter [0, 16] - [0, 30]
name: identifier [0, 16] - [0, 22]
ERROR [0, 23] - [0, 24]
identifier [0, 23] - [0, 24]
type: type_identifier [0, 26] - [0, 30]
body: postfix_expression [0, 35] - [8, 6]
block [0, 35] - [6, 1] …

Add inline if, match, def, parameters

---

corpus/definitions.txt
grammar.js
queries/highlights.scm
test/highlight/scala3.scala

Closes #78
Closes #79 
Closes #75 
Low hanging fruit.
Getting those modifiers consistent with the spec would be good, but for the purposes of highlighting IMO it's not worth splitting them out (I tried - it causes tons of conflicts, so needs thought)

Transparent, open, infix

---

corpus/expressions.txt
grammar.js
script/smoke_test.sh

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/123
Problem
-------
Guard `if something` isn't supported in the for expression.
Solution
--------
This implements it.

Fixes for expression

---

corpus/definitions.txt
grammar.js
queries/highlights.scm
script/smoke_test.sh
test/highlight/scala3.scala

Closes #76 
For consistency, I renamed import_selectors to namespace_selectors to share them with exports.
This will break with old queries.
That said, given how sensitive they are (any node/keyword not present in the grammar causes highlighting to break), we've broken them a while back.
We'll sync them to nvim-treesitter soon.

Export clauses

---

queries/highlights.scm
test/highlight/basics.scala
test/highlight/scala3.scala

Problem
-------
Currently storage related modifiers use keyword.
Solution
--------
We should use `storageclass` for `private`, `protected`, and `inline`. See also https://www.sublimetext.com/docs/scope_naming.html#storage
> Keywords that affect the storage of a variable, function or data structure should use the following scope. Examples include static, inline, const, public and private.

Use storageclass

---

corpus/types.txt
grammar.js
test/highlight/basics.scala

I hope that it isn't too late to join the tree-sitter party :)
This PR adds supports for structural types which allows for using type projections on anonymous structural types that are usually used when working with a higher-kinded types without kind projector.

Add support for structural types

---

corpus/definitions.txt
corpus/expressions.txt
grammar.js
queries/highlights.scm
test/highlight/scala3.scala

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/127
This is on top of https://github.com/tree-sitter/tree-sitter-scala/pull/131
Problem
-------
Currently our grammar does not support the fewer braces syntax, which basically lets us pass the last argument as a block after `:`.
Solution
--------
This implements fewer braces support for call_expression, infix_expression, with and without the lambda start.

SIP-44 Fewer braces support

---

corpus/definitions.txt
corpus/types.txt
grammar.js
script/smoke_test.sh

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/53
Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/56
Problem
-------
1. In Scala 3, extends clause can be comma separated.
2. In Scala 2 or 3 extends clause can ctor with parameters:
`class D with E(x) with F(y)`.
Solution
--------
`extends` is now followed by *constructor applications* separated by
either `with` or `,` as opposed to treating them as a compound type.

Fixes extends clause

---

corpus/types.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/3
Problem
-------
Currently singleton types are treated as `stable_type_identifier`.
Solution
--------
This adds `singleton_type`.

Singleton type

---

queries/highlights.scm
test/highlight/basics.scala
test/highlight/scala3.scala

NOTE that there are still out of sync a bit. The small change that was added in from the fewer braces support isn't yet in nvim-treesitter, but once we generate again after https://github.com/tree-sitter/tree-sitter-scala/pull/147, then I'll fully sync that back.

chore: sync highlights back with nvim-treesitter

---

.github/workflows/sync.yml

I was about to sync and send in a pr again, but I figured why not just automate this. This change adds a new CI job that will run every morning and detect if there are changes. If so, it will commit them and send in a pr.

feat: add in a job to automatically generate and sync daily

---

corpus/definitions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/41
Problem
-------
1. class constructor should accept annotation, but it doesn't.
2. Apparently Scala 3 does allow zero, one, or multiple parameter list
to an annotation, and differentiated between the class parameter by
its lack of type ascription.
Solution
--------
1. Add optional annotation for constructor. At this point, we can at
least parse the code with annotation on the ctor.
2. Unfortunatley, however, tree-sitter doesn't make enough lookahead to
distinguish postfix expr or ascription expression `(x: Int)`,
for now the class parameters will end up being parsed as arguments to
the annotation.

Fixes annotation, sort of

---

.github/workflows/fuzz.yml
src/stack.h
test/test-stack.c

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/159
Ref https://github.com/nvim-treesitter/nvim-treesitter/issues/4170
Problem
-------
The buffer given for payload serialization is 1024, but we are currently using (1024 + 3) * sizeof(int)
Solution
--------
Reduce it way down.

Fixes buffer overrun

---

.github/workflows/fuzz.yml
src/scanner.c

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/159
Problem
-------
tree-sitter-scala crashes under mysterious conditions. gdb seems to indicate that it happens around `get_column`.
Solution
--------
Avoid calling `get_column` when it's at the end of file. That seems to satisfy fuzz.

Fixes crash, take 2

---

grammar.js
queries/highlights.scm
test/highlight/basics.scala

_The problem_
Currently when you come across string interpolation you don't get any
special highlighting for the actual interpolator meaning:
```scala
ivy"com.lihaoyi::os-lib:0.9.0"
```
Is all colored the same.
_The Solution_
The pr makes 2 changes.
- The `identifier` we use for the interpolator now becomes a field for
no reason other than I thought it'd be nice to just give it a name
- A hightlight query that captures it and assigns it to `function.call`.

feat: add an explicit interpolator field

---

corpus/expressions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/132
Problem
-------
Currently pattern match with guard doesn't parse.
Solution
--------
This implements it by creating an intermediate node called `_case_pattern` with right associativity.
Note
-----
```
$ diff -U 0 main-reports/report-scala2-compiler.txt report-scala2-compiler.txt | rg '^[+-]\w+'
4:-scala/tools/nsc/ast/DocComments.scala                                        (ERROR [314, 32] - [567, 0])
5:+scala/tools/nsc/ast/DocComments.scala                                        (ERROR [314, 32] - [319, 2])
7:-scala/tools/nsc/ast/parser/TreeBuilder.scala                                 (ERROR [143, 60] - [143, 61])
10:+scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala                     (ERROR [560, 6] - [627, 4]) …
```

Fixes pattern match with guard

---

queries/highlights.scm
test/highlight/basics.scala
test/highlight/scala3.scala

This is in reference to the conversation that was in
https://github.com/tree-sitter/tree-sitter-scala/discussions/168 around
imports and the coloring of the final part. Taken from Eugene's comment,
which made a lot of sense to message
> In Scala we have namespace for terms and types, and they can each
> define the same name, often encouraged as "companion object", so at the
> point of import statement it's ambiguous.
This is relevant in the import case, but I also think I agree with it
most of the time when you have an uppercase identifier. While there may
be times this isn't the case, I think it's a safe default.
If we agree on this, I'll open a pr in nvim-treesitter so that test passes.

refactor(queries): change uppercase from constant to type

---

corpus/definitions.txt
grammar.js

In Scala 3, you can rename a single identifier without the curly braces if you use `as`
Doesn't work with `=>`

Fix `as` import renaming in Scala 3

---

corpus/definitions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/178
Problem
-------
Package declaration with semicolon fails to parse.
Solution
--------
This adds an optional semicolon to fix that.

Fix semicolon on package

---

corpus/literals.txt
grammar.js

I noticed that syntax highlighting breaks when `_` is present in integer literals. 
This PR fixes that.

fix: Correctly handle _ separator in integer literals

---

.github/workflows/ci.yml
bindings/rust/lib.rs
package.json
queries/scala/highlights.scm
queries/scala/locals.scm
test/highlight/basics.scala
test/highlight/scala3.scala

I noticed that values from interpolated strings are not highlighted correctly:
In order to have correct hl (highlight) group assigned I had to introduce scope tracking feature from the treesitter. After that some hl tests started failing. 
Since some of the changes might be controversial I breakdown them here:
1. in `self: X =>` `self` had a `type` hl group previously. I dunno why. I changed it to `parameter`
2. in `export scanUnit.scan` `scanUnit` was a `namespace` but it is declared few lines above as a variable hence it should has the same hl group as its definition. 
According to the treesitter documentation:
> Good syntax highlighting helps the reader to quickly distinguish between the different types of entities in their code. Ideally, if a given entity appears in multiple places, …

fix: Incorrect string interpolation highlighting group

---

package.json

**Problem**
CI is failing on Ubuntu 20.04.
Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/211
See also https://github.com/tree-sitter/tree-sitter/issues/2272
**Solution**
Try downgrading tree-sitter-cli.

Downgrade tree-sitter-cli

---

default.nix

21.05 is already 2 years old. Switching to 22.11 will make sure that binaries are still in the public cache. 
~In addition I added python3 which seems to by needed internally by npm. I didn't notice that before because I had python globally installed.~
I also found out that on the nixos that is more strict regarding the globabl packages tree-sitter installed via npm no longer works. I switched to use tree-sitter from the upstream.

chore: Update nixpkgs to 22.11 and add python3 to devshell

---

corpus/definitions.txt
grammar.js
src/grammar.json

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/121 and https://github.com/tree-sitter/tree-sitter-scala/issues/208
Both structural and alias anonymous given instances are being parsed correctly with this change:
There is an extra change: first commit formats `corpus/definitions.txt` with `tree-sitter test -u` of version 0.20.8 (the most recent)
Given instances can have an optional signature:
```
optional(seq(
$._function_constructor,
':',
)),
```
E.g. ` A(using B)` in a signature of the given
```scala
given A(using B): C = ???
```
Despite being optional, it was also matched by the tree-sitter for givens without a signature, consuming tokens that should be consumed either by _annotated_type of _structural_instance:
```scala
given C = ???
```
It has something to do with the …

Fix parsing for a few given cases

---

corpus/definitions.txt
grammar.js
src/grammar.json
src/node-types.json

Problem
-------
`$.parameters` required each param to have a name, so `using` clauses like `def x(using X =:= X)` failed to parse
Solution
-------
Introduce `$._using_parameters_clause`, which allows anonymous parameters
Resolves https://github.com/tree-sitter/tree-sitter-scala/issues/187

fix: Anonymous parameters in `using` clauses

---

corpus/expressions.txt
src/scanner.c

Resolves https://github.com/tree-sitter/tree-sitter-scala/issues/188, https://github.com/tree-sitter/tree-sitter-scala/issues/199
Problem:
-------
Code like
```scala
if true ()
else ()
```
or
```scala
a
.b
// comment
.c
```
is not parsed correctly, for extra `$._automated_semicolon` tokens,
which are produced after newlines
Solution:
-------
Tweak `scanner.c` to stop producing AUTOMATED_SEMICOLON tokens when
encountering comments, else/catch clauses, etc.
Extra changes:
-------
corpus/expressions.txt formatted with `tree-sitter test -u` in the first commit
Note:
-------
The following code still won't be parsed
```scala
a
/* comment */ .b
```
as I haven't figured out a way both to parse it and code like
```scala
val a = 1
/* comment */ val b = 2
```
where AUTOMATED_SEMICOLON is needed to …

fix: Handle newlines and comments in the middle of expressions

---

corpus/definitions.txt
grammar.js
src/grammar.json
src/node-types.json

Closes https://github.com/tree-sitter/tree-sitter-scala/issues/202
Problem
-------
Derives clause is only defined for enums, but not for classes and objects
Solution
-------
Include optional `$.derives_clause` in class and object definitions
Concerns
-------
This change increases `tree-sitter gen` execution time by ~50 percent (while not growing the size of  `parser.c` significantly). This slowdown is similar to to the one from optional branches of  else-clause in `if_expression`, catch-clause of in `try_expression`, etc.
I've opened a discussion on this topic some time ago, but no progress there https://github.com/tree-sitter/tree-sitter/discussions/1948

Derives clause for classes and objects

---

.gitignore
Package.swift
bindings/swift/TreeSitterScala/scala.h

Hi friends! Me again :)
This adds Swift bindings and Swift Package Manager (SPM) support. This should require no maintenance on your part, and should not impact the actual parsers in any way. Other similar changes were made here:
https://github.com/tree-sitter/tree-sitter-go
https://github.com/tree-sitter/tree-sitter-c
https://github.com/tree-sitter/tree-sitter-haskell

SPM support

---

.gitignore
script/smoke_test.sh

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/238
Problem
-------
Unfortunately the smoke test hasn't been accurate. Apparently it's been looking at only the top directories.
Solution
--------
This should fix it.

Fix smoke test

---

corpus/literals.txt
src/scanner.c

Resolves https://github.com/tree-sitter/tree-sitter-scala/issues/225
Problem
-------
Strings like `"""""""` are valid in scala, but not in the grammar
Solution
-------
In `scanner.c` emit multi-line string only when at least 3 closing quotes found and the next lookahead is not a quote
Also, corpus/literals.txt was formatted with `tree-sitter test -u`

Allow quotes to be last characters of multi-line string

---

corpus/types.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/203
Problem
-------
The grammar assumes upper type bound to go before lower type bound.
Although, in Scala it's the opposite:
```
TypeBounds ::= [‘>:’ Type] [‘<:’ Type]
```
Solution
-------
Swap type bounds' order in the grammar
Also, `corpus/types.txt` is formatted with `tree-sitter test -u`

Correct type bounds

---

corpus/definitions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/228
Problem
-------
By-name parameters in class definitions were not supported:
```scala
class A(a: => B)
```
Solution
-------
Support by-name parameters by changing the rule describing class parameter type from `$._type` to `$._param_type`

By-name class parameters

---

corpus/definitions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/201
Problem
-------
Annotations on Scala 3 enums and their cases are not supported, e.g.
```scala
@A enum E:
@A("") @B case A
```
Solution
-------
Allow annotations in enum definitions

Annotations on enums

---

corpus/definitions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/230
Problem
-------
Self-types are not parsed in braceless trait definitions:
```scala
trait A:
this: B =>
````
Solution
-------
Move existing `$.self_type` rule in trait definition into indented scope.
Rebalance `$.self_type` precedence.
Without explicit precedence it looses to `$.call_expression` in
```scala
trait A {
self: B =>
def f = ""
}
```
With static precedence instead of dynamic it leads to errors in
definitions like:
```scala
class A
x: Int // this should be $.ascription_expression
enum B:
case C
```

Self-types in braceless trait definitions

---

corpus/expressions.txt
grammar.js

Resolves https://github.com/tree-sitter/tree-sitter-scala/issues/198
Problem
-------
Top-level expressions are not supported. However, it's a valid case for Scala scripts or sbt configurations
Solution
-------
Now that AUTOMATIC_SEMICOLON tokens are handled at the top-level enabling top-level expressions is done by including `$.expression` into `$._top_level_definition`

Top-level expressions

---

corpus/comments.txt
grammar.js
queries/scala/highlights.scm
test/highlight/comments.scala

Implements https://github.com/tree-sitter/tree-sitter-scala/issues/189
Summary
-------
Single line `$.comment` is split into a choice of `$._comment_text` and `$.using_directive` to parse a structure of comments like
```
//> using scala 3.3.0
```
Highlighted example:
with highlight queries:
```
(using_directive_key) @parameter
(using_directive_value) @string
```

Support Scala CLI using directives

---

queries/scala/highlights.scm
test/highlight/comments.scala

As per a quick conversation on nvim-metals discord channel - block comments didn't get highlighting query added to them when they were split into their own thing, as per @keynmol :
> I also found the commit where it slipped through the cracks - the comment node got split but the highlighting query wasn't added: https://github.com/tree-sitter/tree-sitter-scala/commit/693c651b509e2654c237a68e52080f0211b4f5bf
This PR rectifies that and adds tests.
Let me know if there's anything else needed here!

Added block comments to the comment highlighting query

---

.git-blame-ignore-revs
.github/workflows/sync.yml
.prettierrc.json
grammar.js
package.json

Problem
--------
There are some whitespaces at the end of the line kind of things.
Solution
--------
This implements formatting using [Prettier](https://prettier.io/).

Use prettier to format JavaScript file

---

.github/workflows/ci.yml
src/scanner.c

See https://github.com/tree-sitter/tree-sitter-scala/pull/287
Problem
-------
There's C code fidelity check in the CI process, but over time it seems to have broken.
`needs.changedfiles.outputs.c` gets triggered for either `src/scanner.c` or the generated `src/parser.c`, then the fidelity check logic expects that `git diff` will be empty.
This actually won't work if you changed both `src/parser.c` and `grammar.js` at the same time.
Solution
--------
The fix is to make a new `changedfiles.outputs.gen`. Now the new
behavior is:
1. If any C code were changed (including `src/parser.c`), run full tests on all 3 Oses.
2. If non-`src/parser.c` C code were changed, run fidelity check on Linux.

Fix C code fidelity check

---

queries/scala/highlights.scm
test/highlight/scala3.scala

Improves compatibility with non-`nvim` tree-sitter implementations.
Since we only have very simple patterns, just switching to `match` should be fine.

Use match? instead of lua-match? for queries

---

corpus/expressions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/302
Problem
-------
Scala 2 macro definition is not supported.
Solution
--------
This adds macro_body as an expression.

Scala 2 macros

---

corpus/definitions.txt
grammar.js

Resolves #323
Summary
----
Support for dot-separated type references in derives clause
```scala
case class A() derives B.C
```

Allow `$.stable_type_identifier` in `derives_clause`

---

corpus/definitions.txt
grammar.js

Resolves #318
Summary
----
Optional trailing `$._automatic_semicolon` in `$._function_cunstructor`. This enables correct parsing of the code like:
```scala
def foo()
: Int = 42
given foo(using foo: Foo)
: Foo = foo
```

Allow return types on new lines in definitions

---

corpus/definitions.txt
grammar.js

Fixes #348
`trait_definition` now includes `_class_definition` which is comprised of extends-clause, derives-clause, and body. This also slightly reduces parser size (from ~890Kb to ~780Kb)

Derives clause for traits

---

src/scanner.c

Resolves #365
Problem
---
Parsing Markdown with nested Scala code using significant indentation crashes with SIGSEGV Example code:
```scala
for
i <- 1 to 10
yield i
```
Solution
---
Stop calling `lexer->get_column` in `scanner.c` without prior eof-checks

Fix crashes inside Markdown

---

corpus/definitions.txt
corpus/expressions.txt
grammar.js

Fixes #366
Rebalance precedences of `match_expression` (which can contain "inline") and `modifiers`

Allow infix inline modifier

---

corpus/definitions.txt
grammar.js

Fixes #374
Also, this case seems to be not covered by the [ebnf](https://docs.scala-lang.org/scala3/reference/syntax.html#)

Allow $.function_declaration as extension body

---

corpus/literals.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/382
Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/380
Previously the character literal was updated copied from that of Rust apparently, but Scala doesn't have curly braces in the character literal. The regex has bug, and it's failing CI.
We do, however, support two 'u' characters.
1. This removes the curly brace variant.
2. Instead, this adds support for `\uu0041`

Fix character literal

---

.editorconfig
.github/workflows/sync.yml
Cargo.toml
binding.gyp
bindings/node/binding.cc
bindings/node/index.d.ts
bindings/node/index.js
bindings/rust/lib.rs
package.json
queries/scala/highlights.scm
script/smoke_test.sh
test/highlight/scala3.scala

I originally sent a PR to bump to tree-sitter 0.22.1, but maybe that's going too ahead.
Here's a PR to bump to tree-sitter 0.21.0.
Ref https://github.com/neovim/neovim/pull/27566

Update tree-sitter to 0.21.0

---

Cargo.toml
package.json

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/384
Ref https://github.com/neovim/neovim/pull/28643

Update tree-sitter to 0.22.6

---

.github/workflows/ci.yml
script/smoke_test.sh

**Problem**
We currently use scala/scala and scala/scala3 to run the smoke test, but the versions are slightly older.
**Solution**
1. This bumps the versions to latest. Thankfully not much regression on the percentage.
2. This also adds lila for testing.

Bump smoke test targets

---

.github/workflows/publish.yml

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/344
NPM packages are not published.
This cherry picks GitHub Action releasing from https://github.com/tree-sitter/tree-sitter-scala/pull/398

ci: Add GitHub Actions to publish

---

grammar.js
test/corpus/types.txt

Allow literal types to be operands of an infix type

---

queries/scala/indents.scm

Sharing queries for proper indents (also fixes problem descirbed in #173).
I'm going to use them for a while and polish before merging
cc @keynmol

Nvim indents

---

src/scanner.c

The cast from buffer which is char* to uint16_t* is a type alias violation.
If tree-sitter-scala is build with UBSAN enabled this is a runtime error.
This PR fixes it by replacing these cast + assignment with just plain old memcpy.

Fix type alias violation in scanner

---

.github/workflows/ci.yml
queries/highlights.scm

Apparently tree-sitter bindings are expected to beccreated manually and are allowed to be hand-edited. Currently it triggers fidelity check.
This relaxes the C code fidelity check so bindings can be updated.

Relax the fidelity check for bindings

---

grammar.js
test/corpus/definitions.txt

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/438
Scala 3.6.2 added interleaving params <https://docs.scala-lang.org/sips/clause-interleaving.html>,
as in term parameters, type parameters, and
using parameters can show up in an arbitrary order.
This adds support for it.

SIP-47 Clause Interleaving support

---

grammar.js
test/corpus/patterns.txt
test/corpus/types.txt

[SIP-58 Named tuples](https://docs3.scala-lang.org/sips/named-tuples.html) are now available as an experimental feature.
This implements a support for them.

SIP-58 Named tuples support

---

grammar.js
test/corpus/expressions.txt
test/corpus/types.txt

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/204
Poly function types and poly function values aren't supported.
This implements it.

Polymorphic function type and lambda expression

---

.github/workflows/ci.yml
.github/workflows/sync.yml
Cargo.toml
package.json
pyproject.toml

See https://github.com/tree-sitter/tree-sitter-scala/pull/454
Currently GitHub CI sync picks up the latest tree-sitter CLI, which will generate parser using the latest.
This pins it to a specific version.

Pin to tree-sitter 0.24.7

---

grammar.js
src/scanner.c
test/corpus/literals.txt

I also slightly changed the definition of `interpolated_string` by
qualifying the open quotes with `token.immediate(…)`. Prior to this
change the rule would incorrectly match `foo ""` as an `interpolated_string_expression`
I ran these changes against all of the `.scala` files in
https://github.com/scala/scala3 and https://github.com/scala/scala.
The files in `scala/scala3` that newly have errors are:
* `tests/neg/fEscapes.scala`
* `tests/neg/unicodeEscapes-interpolations.scala`
* `tests/pos/multiLineOps.scala`
* `tests/run/i14164.scala`
The first two are tests containing examples of invalid escape
sequences that are expected to fail. `multiLineOps.scala` contains a
line `send_! "!"` that now parses with an error. Previously this
parsed as an `interpolated_string_expression`, which is also …

Support for string escapes

---

.github/workflows/ci.yml
grammar.js
test/corpus/definitions.txt

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/469
packages are treated to be top-level only,
so the nested ones aren't parsed correctly.
This moves packages into definition so they can be nested.

fix: Fix nested packages

---

grammar.js
test/corpus/definitions.txt

[Modularity Improvements](https://docs.scala-lang.org/scala3/reference/experimental/modularity.html) brought a new soft modifier for `val`s, both in constructor argument declarations and local val declarations.
Corresponding Scala 3 grammar changes:
```
ClsParam  ::=  {Annotation} [{Modifier | ‘tracked’} (‘val’ | ‘var’)] Param
```
```
LocalModifier     ::=  ‘tracked’
```

feat: `tracked` soft modifier
