tree-sitter/tree-sitter-scala

Cargo.toml
package.json

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/49
Once this is merged, I'll tag the commit.

Bump to 0.19.1

---

corpus/definitions.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/74

Extension method support

---

corpus/definitions.txt
grammar.js
script/smoke_test.sh
test/highlight/basics.scala

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/114
Picking off a commit from @keynmol's branch.

Scala 2/3: Self-types

---

src/grammar.json
src/node-types.json

Generated from fd05f09043051c82fba695aa95cee9c534fbc533

chore: generate latest changes

---

test/highlight/scala3.scala

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/59

Add tests for optional braces highlights

---

corpus/types.txt
grammar.js

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/144
This adds support for context function.

Context function

---

test/highlight/basics.scala
test/highlight/scala3.scala

I was confirming a couple things locally so figured
I'd just push these up.

test: just a few more highlight tests

---

corpus/definitions.txt
corpus/expressions.txt
corpus/literals.txt
corpus/types.txt
grammar.js
script/smoke_test.sh

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/157
Problem
-------
Trailing commas are not supported.
Solution
--------
This adds support for that.

Trailing commas

---

corpus/expressions.txt
grammar.js
script/smoke_test.sh

String interpolation case pattern

---

corpus/definitions.txt
grammar.js
script/smoke_test.sh

Abstract type definitions

---

script/smoke_test.sh

Add complexity check to smoke_test.sh

---

corpus/types.txt
grammar.js
test/highlight/scala3.scala

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/205
This implements support for Scala 3 match types.

Match type

---

corpus/types.txt
grammar.js

Re-creating a new PR, since I was not able to figure out a clean way to remove the `src/*` files from the previous PR #311. Hence, I've closed that one, and opened this one afresh. The modifications remains the same, but please feel free to recheck.
Apologies for the noise with multiple PRs

Add support for Type Lambdas

---

src/scanner.c
src/stack.h
test/test-stack.c

the only change I might be unsure about is changing the nul byte check to an eof check, I'm assuming scala is sane and doesn't allow for that anywhere but eof

Tidy up scanner and generate w/ master

---

corpus/expressions.txt
grammar.js

Fixes #303
Now binding is a choice from identifier and wildcard

Wildcards in tuple bindings

---

corpus/comments.txt
grammar.js

Support shebang.

---

corpus/definitions.txt
grammar.js

Allow for abstract givens

---

.github/workflows/publish.yml

The main branch seems to be broken.

Pin package-npm to an older version

---

script/smoke_test.sh

This brings back the complexity ceiling

Fix check_complexity

---

.github/workflows/sync.yml

Run cron action only on the tree-sitter repo

---

.github/workflows/ci.yml
.github/workflows/sync.yml
package-lock.json
package.json

`npm run build` seems to overwrite `package.json`.
This moves the build and test code into GitHub Actions YAML.

Fix build, take 2

---

.github/workflows/ci.yml
.prettierrc.json
package-lock.json
package.json
script/smoke_test.sh

Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/434

Reinstate prettier to fix the sync job

---

test/corpus/expressions.txt

This add a test for [SIP-62](https://docs.scala-lang.org/sips/better-fors.html), which allows for comprehension that starts with an alias.

test: Add test for SIP-62 for

---

.gitignore
queries/tags.scm
test/tags/basics.scala
tree-sitter.json

feat: Add tags.scm queries
